package com.aep.cx.utils.enums;

public enum MessageTypeGlobal {
	POWERPAY, PAYMENT,BILLDUE,CPPENROLLMENT,DISCONNECTED,DISCONNECTISSUED,
	INHOUSEPAPERLESS,RECONNECTISSUED,RECONNECTED,RETURNCHECK,OUTAGE, 
	SUBSCRIPTION, PSOVPP, VPPEVENT,NONE, CRSPEMAIL, REGISTRATION
}
